import { Download, Info, ScanLine, ShieldCheck } from 'lucide-react'
import xrayImage from '../../assets/xray.png'

const probability = [
  { label: 'KL 0-1', description: 'Normal / Doubtful', value: 1.6, color: '#24936f' },
  { label: 'KL 2-3', description: 'Mild / Moderate', value: 79.6, color: '#19745f' },
  { label: 'KL 4', description: 'Severe', value: 18.8, color: '#4285dc' },
]

export function PredictionSummary() {
  return <section className="rounded-xl border border-[#dceae6] bg-gradient-to-r from-white to-[#eff9f5] p-6 shadow-sm shadow-[#1a5a49]/5"><div className="flex flex-col items-center gap-6 sm:flex-row"><div className="grid h-32 w-32 shrink-0 place-items-center rounded-full" style={{ background: 'conic-gradient(#19745f 0 79.6%, #dcece7 79.6% 100%)' }}><div className="grid h-24 w-24 place-items-center rounded-full bg-white text-center"><strong className="text-2xl">79.6%</strong><span className="text-[10px] text-slate-600">Confidence</span></div></div><div><p className="text-xs font-bold text-[#17614e]">PREDICTED KL GRADE</p><div className="mt-2 flex flex-wrap items-center gap-3"><h2 className="text-4xl font-bold tracking-tight text-[#155d4b]">KL 2-3</h2><span className="rounded-md bg-[#e3f4ed] px-2.5 py-1 text-xs font-bold text-[#19745f]">Mild to Moderate</span></div><p className="mt-3 max-w-xl text-sm leading-relaxed text-slate-700">Mild to moderate osteoarthritis — definite osteophytes, joint space narrowing.</p></div></div></section>
}

export function ProbabilityChart() {
  return <section className="rounded-xl border border-[#dceae6] bg-white p-5 shadow-sm shadow-[#1a5a49]/5"><h2 className="flex items-center gap-2 text-sm font-bold">Class Probabilities <Info size={14} className="text-slate-400" /></h2><div className="mt-5 flex h-52 items-end justify-around gap-5 border-b border-l border-[#e0ebe7] px-5 pt-4">{probability.map(({ label, description, value, color }) => <div key={label} className="flex h-full flex-1 flex-col justify-end text-center"><div className="relative rounded-t-md" style={{ height: `${value}%`, backgroundColor: color }}><span className="absolute -top-6 left-1/2 -translate-x-1/2 text-xs font-bold">{value}%</span></div><strong className="mt-3 text-xs">{label}</strong><span className="mt-1 text-[11px] text-slate-600">{description}</span></div>)}</div></section>
}

export function ImagingPanel() {
  return <section className="rounded-xl border border-[#dceae6] bg-white p-4 shadow-sm shadow-[#1a5a49]/5"><h2 className="flex items-center gap-2 text-sm font-bold"><ScanLine size={16} className="text-[#19745f]" />Grad-CAM Visualization <Info size={13} className="text-slate-400" /></h2><div className="mt-4 grid grid-cols-2 gap-3"><figure><figcaption className="mb-2 text-center text-[11px] font-medium">Original X-ray</figcaption><div className="h-44 rounded-md bg-slate-950" style={{ backgroundImage: `url(${xrayImage})`, backgroundPosition: 'left center', backgroundSize: '200% 100%' }} /></figure><figure><figcaption className="mb-2 text-center text-[11px] font-medium">AI Attention Map</figcaption><div className="h-44 rounded-md bg-slate-950" style={{ backgroundImage: `url(${xrayImage})`, backgroundPosition: 'right center', backgroundSize: '200% 100%' }} /></figure></div><div className="mt-4 rounded-lg bg-[#f5f8f7] p-3"><h3 className="text-xs font-bold">Raw Probability Table</h3>{probability.map(({ label, description, value, color }) => <div key={label} className="mt-3 grid grid-cols-[145px_1fr_42px] items-center gap-2 text-[11px]"><span>{label} ({description})</span><div className="h-1.5 overflow-hidden rounded bg-[#eaf0ee]"><div className="h-full rounded" style={{ width: `${value}%`, backgroundColor: color }} /></div><span className="text-right font-semibold">{value}%</span></div>)}</div></section>
}

export function ReportFooter() {
  return <section className="grid gap-4 xl:grid-cols-[1.7fr_.8fr]"><div className="rounded-xl border border-[#dceae6] bg-white p-5 shadow-sm shadow-[#1a5a49]/5"><h2 className="text-sm font-bold">Interpretation Guide</h2><div className="mt-4 grid gap-3 text-[11px] sm:grid-cols-3"><p><b className="text-[#19745f]">● KL 0-1 (Normal / Doubtful)</b><br />No or doubtful osteoarthritis. Normal joint space.</p><p><b className="text-[#b27a07]">● KL 2-3 (Mild / Moderate)</b><br />Definite osteophytes with possible joint space narrowing.</p><p><b className="text-[#c94343]">● KL 4 (Severe)</b><br />Large osteophytes, marked joint space narrowing and deformity.</p></div><div className="mt-4 flex gap-2 rounded-lg bg-[#edf8f4] p-3 text-[11px] text-slate-600"><ShieldCheck size={17} className="shrink-0 text-[#19745f]" />This prediction is generated by KOA-AI and is intended to assist radiologists and healthcare professionals. Final diagnosis should be made by a qualified expert.</div></div><div className="rounded-xl border border-[#dceae6] bg-white p-5 text-xs shadow-sm shadow-[#1a5a49]/5"><h2 className="text-sm font-bold">Analysis Information</h2><dl className="mt-4 space-y-3"><div className="flex justify-between gap-3"><dt>Analysis ID</dt><dd className="font-semibold">#KOA-2025-05-16-0012</dd></div><div className="flex justify-between gap-3"><dt>Model Used</dt><dd className="font-semibold">EfficientNet-B3</dd></div><div className="flex justify-between gap-3"><dt>Input Image Size</dt><dd className="font-semibold">1024 × 1024</dd></div></dl></div></section>
}

export function ReportActions() {
  return (
    <div className="flex flex-wrap gap-3">
      <button
        onClick={() => window.print()}
        className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#dceae6] bg-white px-6 py-3 text-sm font-semibold text-[#17614e] shadow-sm transition hover:bg-[#f2faf7]"
      >
        <Download size={18} />
        Download Report
      </button>
    </div>
  )
}
